openapi: 3.0.0
info:
  title: TaxAnalystPro Custom API
  version: 1.0.2
  description: Custom API for S-Corp buyout and tax scenario analysis (unique domain)

servers:
  - url: https://taxanalystpro-custom.example.com

paths:
  /analyze-scorp:
    post:
      summary: Analyze S-Corp buyout scenario
      operationId: analyzeScorpScenario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                scenarioType:
                  type: string
                  example: buyout
                buyoutAmount:
                  type: number
                  example: 1100000
                buyoutYears:
                  type: integer
                  example: 5
                state:
                  type: string
                  example: VA
                w2Percentage:
                  type: number
                  example: 0.6
                businessExpenses:
                  type: number
                  example: 10000
                retirementPlan:
                  type: string
                  example: Solo401k
                ptetOptIn:
                  type: boolean
                  example: true
                niitApplicable:
                  type: boolean
                  example: true
              required:
                - scenarioType
                - buyoutAmount
                - buyoutYears
                - state
                - w2Percentage
                - businessExpenses
                - retirementPlan
                - ptetOptIn
                - niitApplicable
      responses:
        '200':
          description: Analysis result
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: Analysis completed successfully
                  details:
                    type: object
                    additionalProperties: true
  /analyze-multi-scenario:
    post:
      summary: Analyze multiple S-Corp tax scenarios
      operationId: analyzeMultiScenario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                scenarios:
                  type: array
                  items:
                    type: object
                    properties:
                      scenarioType:
                        type: string
                        example: buyout
                      buyoutAmount:
                        type: number
                        example: 1100000
                      buyoutYears:
                        type: integer
                        example: 5
                      state:
                        type: string
                        example: VA
                      w2Percentage:
                        type: number
                        example: 0.6
                      businessExpenses:
                        type: number
                        example: 10000
                      retirementPlan:
                        type: string
                        example: Solo401k
                      ptetOptIn:
                        type: boolean
                        example: true
                      niitApplicable:
                        type: boolean
                        example: true
                    required:
                      - scenarioType
                      - buyoutAmount
                      - buyoutYears
                      - state
                      - w2Percentage
                      - businessExpenses
                      - retirementPlan
                      - ptetOptIn
                      - niitApplicable
              required:
                - scenarios
      responses:
        '200':
          description: Multi-scenario analysis result
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        scenarioType:
                          type: string
                        result:
                          type: string
                        details:
                          type: object
                          additionalProperties: true
